spring:
  datasource:
    url: jdbc:postgresql://dpg-ckal4p6gtj9c739ugvi0-a.frankfurt-postgres.render.com:5432/carpartshub
    username: carpartshub_user
    password: N21wRMHnYsaNZxWVoGRsOYiLzDqZjr53
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB


  mail:
    host: smtp.gmail.com
    port: 587
    username: <your email>
    password: <your password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days